import pandas as pd
import numpy as np
import gymnasium as gym
from gymnasium import spaces
import torch.nn as nn
from stable_baselines3 import PPO
from stable_baselines3.common.torch_layers import BaseFeaturesExtractor
from stable_baselines3.common.vec_env import DummyVecEnv

from data.market_data import fetch_and_process_data

TICKERS = [
    "AXP",
    "AMGN",
    "AAPL",
    "BA",
    "CAT",
    "CSCO",
    "CVX",
    "GS",
    "HD",
    "HON",
    "IBM",
    "INTC",
    "JNJ",
    "KO",
    "JPM",
    "MCD",
    "MMM",
    "MRK",
    "MSFT",
    "NKE",
    "PG",
    "UNH",
    "CRM",
    "VZ",
    "V",
    "WMT",
    "DIS",
    "GOOGL",
    "NVDA",
    "AMZN",
]

TRAIN_START = "2012-07-27"
# TRAIN_END = "2018-12-31"
TEST_START = "2019-01-01"  # Split date.
TEST_END = "2023-01-24"

NEWS_FILE = "./data/fnspid_embeddings.csv"
WINDOW_SIZE = 10


def merge_data():
    market_data = fetch_and_process_data(TICKERS, TRAIN_START, TEST_END)
    market_data.reset_index(inplace=True)
    market_data.columns = [c.lower() for c in market_data.columns]

    if "date" not in market_data.columns and "index" in market_data.columns:
        market_data.rename(columns={"index": "date"}, inplace=True)
    market_data["date"] = pd.to_datetime(market_data["date"]).dt.date

    news_data = pd.read_csv(NEWS_FILE)
    news_data["date"] = pd.to_datetime(news_data["date"]).dt.date

    merged = pd.merge(market_data, news_data, on=["date", "ticker"], how="left")
    merged = merged.sort_values(["date", "ticker"]).reset_index(drop=True)

    # Clean NaNs generated by indicators (ex. first 26 days for MACD).
    merged = merged.fillna(0)
    print(f"Final shape: {merged.shape}")

    return merged


class LSTMFeatureExtractor(BaseFeaturesExtractor):
    def __init__(self, observation_space, features_dim=256):
        super().__init__(observation_space, features_dim)

        self.window_size = WINDOW_SIZE
        self.input_dim = observation_space.shape[0] // self.window_size
        self.lstm = nn.LSTM(
            input_size=self.input_dim, hidden_size=features_dim, batch_first=True
        )

    def forward(self, observations):
        batch_size = observations.shape[0]
        reshaped = observations.view(batch_size, self.window_size, self.input_dim)
        lstm_out, _ = self.lstm(reshaped)
        return lstm_out[:, -1, :]


class StockTradingEnv(gym.Env):
    def __init__(self, df, mode="train"):
        super().__init__()

        self.dates = sorted(df["date"].unique())
        if mode == "train":
            self.dates = [d for d in self.dates if str(d) < TEST_START]
        else:
            self.dates = [d for d in self.dates if str(d) >= TEST_START]

        self.df = df[df["date"].isin(self.dates)].copy()
        self.tickers = df["ticker"].unique()
        self.n_tickers = len(self.tickers)

        self.meta_cols = ["date", "ticker"]
        self.feature_cols = [c for c in df.columns if c not in self.meta_cols]

        # Flatten features into one vector per day per stock.
        self.daily_obs = []
        self.daily_prices = []

        print(f"Pre-processing {mode} environment...")
        for d in self.dates:
            day_df = self.df[self.df["date"] == d].sort_values("ticker")

            if len(day_df) != self.n_tickers:
                continue

            obs_vec = day_df[self.feature_cols].values.flatten()
            self.daily_obs.append(obs_vec)
            self.daily_prices.append(day_df["close"].values)

        self.daily_obs = np.array(self.daily_obs, dtype=np.float32)
        self.daily_prices = np.array(self.daily_prices, dtype=np.float32)

        obs_dim = self.daily_obs.shape[1]
        self.observation_space = spaces.Box(
            low=-np.inf, high=np.inf, shape=(WINDOW_SIZE * obs_dim,), dtype=np.float32
        )
        self.action_space = spaces.Box(
            low=-1, high=1, shape=(self.n_tickers,), dtype=np.float32
        )

        self.current_step = 0
        self.cash = 1000000
        self.holdings = np.zeros(self.n_tickers)
        self.portfolio_value = 1000000
        self.peak_portfolio_value = 1000000

    def reset(self, seed=None):
        super().reset(seed=seed)
        self.current_step = WINDOW_SIZE
        self.cash = 1000000
        self.holdings = np.zeros(self.n_tickers)
        self.portfolio_value = 1000000
        self.peak_portfolio_value = 1000000
        return self._get_obs(), {}

    def _get_obs(self):
        window = self.daily_obs[self.current_step - WINDOW_SIZE : self.current_step]
        return window.flatten()

    def step(self, actions):
        current_prices = self.daily_prices[self.current_step]

        # Scale actions (-1 to 1) -> (-100 to 100 shares) by hmax=100.
        hmax = 100
        trades = actions * hmax

        for i, trade in enumerate(trades):
            price = current_prices[i]
            cost = trade * price
            self.holdings[i] += trade
            self.cash -= cost

        # Reward = Profit - Drawdown_Penalty
        new_value = self.cash + np.sum(self.holdings * current_prices)
        profit = new_value - self.portfolio_value

        self.peak_portfolio_value = max(self.peak_portfolio_value, new_value)
        # Drawdown formula.
        drawdown = (self.peak_portfolio_value - new_value) / self.peak_portfolio_value
        penalty = drawdown * 0.01

        reward = profit * 1e-4 - penalty

        self.portfolio_value = new_value
        self.current_step += 1

        terminated = self.current_step >= len(self.daily_obs) - 1

        return (
            self._get_obs(),
            reward,
            terminated,
            False,
            {"portfolio_value": self.portfolio_value},
        )


data = merge_data()
env = DummyVecEnv([lambda: StockTradingEnv(data, mode="train")])

model = PPO(
    "MlpPolicy",
    env,
    policy_kwargs={
        "features_extractor_class": LSTMFeatureExtractor,
        "features_extractor_kwargs": {"features_dim": 256},
        "net_arch": dict(pi=[64, 64], vf=[64, 64]),
    },
    learning_rate=0.0003,
    batch_size=128,
    gamma=0.99,
    gae_lambda=0.95,
    clip_range=0.2,
    verbose=1,
)

model.learn(total_timesteps=100000)
model.save("lstm_ppo_trader")
